import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';
import { IReport } from '@/types/report';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 30,
    borderBottom: '2pt solid #000000',
    paddingBottom: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    color: '#000000',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#666666',
    marginBottom: 4,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#111827',
    marginBottom: 12,
    borderBottom: '1pt solid #e5e7eb',
    paddingBottom: 6,
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#374151',
    marginBottom: 8,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f4f6',
    padding: 12,
    borderRadius: 6,
    marginBottom: 20,
  },
  scoreLabel: {
    fontSize: 14,
    fontWeight: 600,
    marginRight: 10,
  },
  scoreValue: {
    fontSize: 18,
    fontWeight: 700,
    color: '#059669', // Emerald 600
  },
  swotGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  swotBox: {
    width: '48%',
    padding: 12,
    border: '1pt solid #e5e7eb',
    borderRadius: 6,
    marginBottom: 16,
  },
  swotTitle: {
    fontSize: 14,
    fontWeight: 600,
    marginBottom: 8,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  bullet: {
    width: 10,
    fontSize: 11,
  },
  itemText: {
    flex: 1,
    fontSize: 11,
    lineHeight: 1.4,
    color: '#374151',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 10,
    color: '#9ca3af',
    borderTop: '1pt solid #e5e7eb',
    paddingTop: 10,
    textAlign: 'center',
  }
});

interface ReportPDFProps {
  report: IReport;
}

const BulletList = ({ items }: { items: string[] }) => (
  <View>
    {items.map((item, i) => (
      <View key={i} style={styles.listItem}>
        <Text style={styles.bullet}>•</Text>
        <Text style={styles.itemText}>{item}</Text>
      </View>
    ))}
  </View>
);

export const ReportPDF = ({ report }: ReportPDFProps) => {
  const data = report.reportData;
  if (!data) return null;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{report.companyName} Due Diligence</Text>
          <Text style={styles.subtitle}>Analysis Type: {report.analysisType}</Text>
          <Text style={styles.subtitle}>Generated: {new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.scoreContainer}>
          <Text style={styles.scoreLabel}>AI Investment Score:</Text>
          <Text style={styles.scoreValue}>{report.aiScore || data.investmentScore}/100</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.text}>{data.executiveSummary || "N/A"}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Market & Risks</Text>
          <Text style={styles.text}>{data.marketAnalysis || "N/A"}</Text>
          <Text style={{ ...styles.text, marginTop: 8, fontWeight: 600 }}>Risk Assessment:</Text>
          <Text style={styles.text}>{data.riskAssessment || "N/A"}</Text>
        </View>
        
        <View style={styles.footer} fixed>
          <Text>Generated by VentureIQ Intelligence Engine</Text>
        </View>
      </Page>

      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>SWOT Analysis</Text>
          <View style={styles.swotGrid}>
            <View style={{ ...styles.swotBox, borderTop: '3pt solid #22c55e' }}>
              <Text style={{ ...styles.swotTitle, color: '#166534' }}>Strengths</Text>
              <BulletList items={data.swot?.strengths || []} />
            </View>
            <View style={{ ...styles.swotBox, borderTop: '3pt solid #ef4444' }}>
              <Text style={{ ...styles.swotTitle, color: '#991b1b' }}>Weaknesses</Text>
              <BulletList items={data.swot?.weaknesses || []} />
            </View>
            <View style={{ ...styles.swotBox, borderTop: '3pt solid #3b82f6' }}>
              <Text style={{ ...styles.swotTitle, color: '#1e40af' }}>Opportunities</Text>
              <BulletList items={data.swot?.opportunities || []} />
            </View>
            <View style={{ ...styles.swotBox, borderTop: '3pt solid #f59e0b' }}>
              <Text style={{ ...styles.swotTitle, color: '#92400e' }}>Threats</Text>
              <BulletList items={data.swot?.threats || []} />
            </View>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Recommendation</Text>
          {data.investmentVerdict && (
            <Text style={{ fontSize: 14, fontWeight: 700, color: '#059669', marginBottom: 6 }}>
              Verdict: {data.investmentVerdict.label}
            </Text>
          )}
          {data.investmentVerdict && (
            <Text style={{ ...styles.text, fontWeight: 600 }}>{data.investmentVerdict.summary}</Text>
          )}
          <Text style={styles.text}>{data.recommendation || "N/A"}</Text>
        </View>

        {data.keyInsights && data.keyInsights.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Key Insights</Text>
            <BulletList items={data.keyInsights} />
          </View>
        )}
        
        <View style={styles.footer} fixed>
          <Text>Generated by VentureIQ Intelligence Engine</Text>
        </View>
      </Page>

      {(data.competitorAnalysis || data.redFlags || data.growthOpportunities || data.scoreBreakdown) && (
        <Page size="A4" style={styles.page}>
          
          {data.scoreBreakdown && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Score Breakdown</Text>
              <View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>
                {[
                  { label: "Market Opportunity", value: data.scoreBreakdown.marketOpportunity },
                  { label: "Product Strength", value: data.scoreBreakdown.productStrength },
                  { label: "Scalability", value: data.scoreBreakdown.scalability },
                  { label: "Competitive Moat", value: data.scoreBreakdown.competitiveMoat },
                  { label: "Risk Level", value: data.scoreBreakdown.riskLevel },
                ].map((stat, i) => (
                  <View key={i} style={{ width: '50%', marginBottom: 12 }}>
                    <Text style={{ fontSize: 11, color: '#666666', marginBottom: 2 }}>{stat.label}</Text>
                    <Text style={{ fontSize: 14, fontWeight: 700 }}>{typeof stat.value === 'number' ? stat.value : (stat.value as any)?.score || 0}/100</Text>
                  </View>
                ))}
              </View>
            </View>
          )}

          {data.redFlags && data.redFlags.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Red Flags & Risks</Text>
              {data.redFlags.map((flag, i) => (
                <View key={i} style={{ marginBottom: 10 }}>
                  <Text style={{ fontSize: 12, fontWeight: 700, color: flag.severity === 'high' ? '#dc2626' : (flag.severity === 'medium' ? '#d97706' : '#2563eb'), marginBottom: 2 }}>
                    [{flag.severity.toUpperCase()}] {flag.title}
                  </Text>
                  <Text style={styles.text}>{flag.description}</Text>
                </View>
              ))}
            </View>
          )}

          {data.growthOpportunities && data.growthOpportunities.length > 0 && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Growth Opportunities</Text>
              {data.growthOpportunities.map((opp, i) => (
                <View key={i} style={{ marginBottom: 10 }}>
                  <Text style={{ fontSize: 12, fontWeight: 700, marginBottom: 2 }}>
                    {opp.title} ({opp.timeframe.replace('-', ' ')})
                  </Text>
                  <Text style={styles.text}>{opp.description}</Text>
                </View>
              ))}
            </View>
          )}

          {data.competitorAnalysis && (
            <View style={styles.section}>
              <Text style={styles.sectionTitle}>Competitor Analysis</Text>
              <Text style={styles.text}>{data.competitorAnalysis.summary}</Text>
              <View style={{ marginTop: 10 }}>
                {data.competitorAnalysis.topCompetitors.map((comp, i) => (
                  <View key={i} style={{ marginBottom: 12, padding: 10, backgroundColor: '#f9fafb', borderRadius: 4 }}>
                    <Text style={{ fontSize: 12, fontWeight: 700, marginBottom: 4 }}>{comp.name}</Text>
                    <Text style={styles.text}><Text style={{ fontWeight: 600 }}>Why:</Text> {comp.reason}</Text>
                    <Text style={{ ...styles.text, marginBottom: 0 }}><Text style={{ fontWeight: 600 }}>Differentiation:</Text> {comp.differentiation}</Text>
                  </View>
                ))}
              </View>
            </View>
          )}
          
          <View style={styles.footer} fixed>
            <Text>Generated by VentureIQ Intelligence Engine</Text>
          </View>
        </Page>
      )}
    </Document>
  );
};
